export const images =[

  {
    thumbnail:"../wallpapers/wallpaper1.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper2.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper3.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper4.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper5.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper6.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper7.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper8.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper9.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper10.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper11.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper12.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper13.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper14.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper15.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper16.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper17.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper18.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper19.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper20.jpg"
  },
  {
    thumbnail:"../wallpapers/wallpaper21.jpg"
  }
]